import { existsSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import type { Command } from "commander";
import type { Entity, StructuralNode, DecisionNode } from "../../entity/types.js";
import { isStructuralNode, isDecisionNode } from "../../entity/types.js";
import { parseEntity } from "../../entity/parser.js";
import { findWhygraphDir } from "./serve.js";

// ============================================================
// Types
// ============================================================

export interface CrossrefResult {
  outputPath: string;
  nodeCount: number;
  decisionCount: number;
}

// ============================================================
// Core Logic
// ============================================================

export function runCrossref(targetDir: string): CrossrefResult {
  const projectDir = findWhygraphDir(targetDir);
  if (!projectDir) {
    throw new Error(`.whygraph/ not found. Run "npx whygraph init" first.`);
  }

  const graphDir = join(projectDir, ".whygraph", "graph");
  const entities = loadEntities(graphDir);

  const nodes = entities.filter(isStructuralNode);
  const decisions = entities.filter(isDecisionNode);

  const idToNode = new Map(nodes.map((n) => [n.id, n]));

  const markdown = buildMarkdown(nodes, decisions, idToNode);

  const outputPath = join(projectDir, ".whygraph", "CONTEXT.md");
  writeFileSync(outputPath, markdown, "utf-8");

  return { outputPath, nodeCount: nodes.length, decisionCount: decisions.length };
}

function loadEntities(graphDir: string): Entity[] {
  if (!existsSync(graphDir)) return [];

  return readdirSync(graphDir)
    .filter((f) => f.endsWith(".md"))
    .flatMap((file) => {
      const content = readFileSync(join(graphDir, file), "utf-8");
      const entity = parseEntity(content);
      return entity !== null ? [entity] : [];
    });
}

function buildMarkdown(
  nodes: StructuralNode[],
  decisions: DecisionNode[],
  idToNode: Map<string, StructuralNode>,
): string {
  const lines: string[] = [
    "# Whygraph Context Snapshot",
    "",
    `_Generated: ${new Date().toISOString()}_`,
    "_This file is auto-generated by `npx whygraph crossref`. Do not edit manually._",
    "",
  ];

  // Structural graph section
  lines.push("## Graph Structure", "");

  const apps = nodes.filter((n) => n.label === "App");
  const features = nodes.filter((n) => n.label === "Feature");
  const components = nodes.filter((n) => n.label === "Component");

  for (const app of apps) {
    lines.push(`- **App** \`${app.id}\` — ${app.name}`);
    for (const feature of features.filter((f) => f.parent === app.id)) {
      lines.push(`  - **Feature** \`${feature.id}\` — ${feature.name}`);
      for (const comp of components.filter((c) => c.parent === feature.id)) {
        lines.push(`    - **Component** \`${comp.id}\` — ${comp.name}`);
      }
    }
  }

  // Orphaned features (no matching app)
  for (const feature of features.filter((f) => !f.parent || !idToNode.has(f.parent))) {
    lines.push(`- **Feature** \`${feature.id}\` — ${feature.name} _(unlinked)_`);
    for (const comp of components.filter((c) => c.parent === feature.id)) {
      lines.push(`  - **Component** \`${comp.id}\` — ${comp.name}`);
    }
  }

  lines.push("");

  // Decisions section
  lines.push("## Decisions", "");

  if (decisions.length === 0) {
    lines.push("_No decisions recorded yet._", "");
  } else {
    for (const d of decisions) {
      lines.push(`### [${d.id}] ${d.title}`);
      lines.push("");

      const affectsLabels = d.affects
        .map((id) => {
          const node = idToNode.get(id);
          return node ? `\`${id}\` (${node.name})` : `\`${id}\``;
        })
        .join(", ");

      lines.push(
        `- **Status:** ${d.status} | **Date:** ${d.date} | **Tags:** ${d.tags.join(", ")}`,
      );
      if (d.affects.length > 0) {
        lines.push(`- **Affects:** ${affectsLabels}`);
      }
      /* v8 ignore next 3 */
      if (d.supersedes) {
        lines.push(`- **Supersedes:** \`${d.supersedes}\``);
      }
      lines.push("");
      lines.push(`> **Context:** ${d.context}`);
      lines.push(`> **Decision:** ${d.decision}`);
      lines.push(`> **Tradeoffs:** ${d.tradeoffs}`);
      lines.push(`> **Alternatives:** ${d.alternatives}`);
      lines.push("");
      lines.push("---");
      lines.push("");
    }
  }

  return lines.join("\n");
}

// ============================================================
// CLI Wiring
// ============================================================

export function registerCrossrefCommand(program: Command): void {
  program
    .command("crossref")
    .description(
      "Generate .whygraph/CONTEXT.md — a graph snapshot for use when MCP is unavailable",
    )
    .option("--json", "Output results as JSON")
    .action((opts: { json?: boolean }) => {
      try {
        const result = runCrossref(process.cwd());

        if (opts.json) {
          process.stdout.write(JSON.stringify(result, null, 2) + "\n");
        } else {
          process.stdout.write(
            `Context snapshot written to ${result.outputPath}\n` +
              `  Nodes: ${result.nodeCount}\n` +
              `  Decisions: ${result.decisionCount}\n`,
          );
        }
      } catch (err: unknown) {
        /* v8 ignore next 1 */
        const message = err instanceof Error ? err.message : String(err);
        if (opts.json) {
          process.stdout.write(JSON.stringify({ error: message }, null, 2) + "\n");
        } else {
          process.stderr.write(`Error: ${message}\n`);
        }
        process.exitCode = 1;
      }
    });
}
